aquasecurity/harbor-scanner-aqua

- .github/workflows/build.yml
- pkg/aqua/command.go
> fix: Do not return error when scannercli returns exit code 4

- Dockerfile
- Makefile
- README.md
> chore: Add CA certificates to Docker image

- README.md
- helm/harbor-scanner-aqua/README.md
- helm/harbor-scanner-aqua/templates/deployment.yaml
- helm/harbor-scanner-aqua/values.yaml
- pkg/aqua/command.go
- pkg/etc/config.go
- pkg/etc/config_test.go
- pkg/harbor/model.go
- pkg/scanner/transformer.go
> feat: Pass --no-verify and --show-negligible flags to scannercli

- .github/workflows/build.yml
- helm/harbor-scanner-aqua/templates/_helpers.tpl
- helm/harbor-scanner-aqua/templates/deployment.yaml
- pkg/http/api/v1/handler.go
- pkg/http/api/v1/handler_test.go
> feat: Add liveness and readiness probes

- helm/harbor-scanner-aqua/values.yaml
- pkg/http/api/server.go
> feat: Configure the minimum version of TLS to 1.2

- README.md
> docs: Document deployment for Docker

- .github/workflows/release.yml
> chore: Use GITHUB_TOKEN instead of GITHUB_REGISTRY_TOKEN

- README.md
- helm/harbor-scanner-aqua/Chart.yaml
- helm/harbor-scanner-aqua/README.md
- helm/harbor-scanner-aqua/values.yaml
> release: Prepare v0.6.0

- helm/harbor-scanner-aqua/Chart.yaml
- helm/harbor-scanner-aqua/values.yaml
> release: Prepare v0.7.0

- Dockerfile
> fix: Install required packages to run scannercli binary

- helm/harbor-scanner-aqua/Chart.yaml
- helm/harbor-scanner-aqua/values.yaml
> release: Prepare v0.7.1

- helm/harbor-scanner-aqua/Chart.yaml
- helm/harbor-scanner-aqua/values.yaml
> release: Prepare v0.8.0

- .github/workflows/build.yml
- .github/workflows/release.yml
- README.md
- helm/harbor-scanner-aqua/README.md
- helm/harbor-scanner-aqua/templates/deployment.yaml
- helm/harbor-scanner-aqua/values.yaml
- pkg/aqua/command.go
- pkg/aqua/command_test.go
- pkg/etc/config.go
- pkg/etc/config_test.go
- pkg/http/api/v1/handler.go
- pkg/http/api/v1/handler_test.go
> fix: Bring back SCANNER_CLI_SHOW_NEGLIGIBLE config

- helm/harbor-scanner-aqua/Chart.yaml
- helm/harbor-scanner-aqua/values.yaml
> release: Prepare v0.8.1

- .github/workflows/build.yml
- helm/harbor-scanner-aqua/Chart.yaml
- helm/harbor-scanner-aqua/values.yaml
> release: Prepare v0.8.2

- README.md
> docs(README): Update Aqua version in the troubleshooting guide

- README.md
- helm/harbor-scanner-aqua/README.md
- helm/harbor-scanner-aqua/templates/deployment.yaml
- helm/harbor-scanner-aqua/values.yaml
- pkg/aqua/command.go
- pkg/aqua/command_test.go
- pkg/etc/config.go
- pkg/http/api/v1/handler.go
- pkg/http/api/v1/handler_test.go
> feat: Allow passing the -D --direct-cc flag to scannercli scan command

- helm/harbor-scanner-aqua/Chart.yaml
- helm/harbor-scanner-aqua/values.yaml
> release: Prepare v0.9.0

- README.md
> docs(README): Update troubleshooting guides

- README.md
- helm/harbor-scanner-aqua/README.md
- helm/harbor-scanner-aqua/templates/deployment.yaml
- helm/harbor-scanner-aqua/values.yaml
> feat: Change the default value of SCANNER_AQUA_USE_IMAGE_TAG to false

- helm/harbor-scanner-aqua/templates/deployment.yaml
- helm/harbor-scanner-aqua/templates/serviceaccount.yaml
> chore(Helm): Use dedicated service account to run adapter's pod

- helm/harbor-scanner-aqua/Chart.yaml
> chore: Update Helm chart from 0.10.0 to 0.10.1

- README.md
> docs: Add note on OpenShift Container Platform

- .github/workflows/build.yml
- .github/workflows/release.yml
- README.md
> chore: Change default branch to main

- helm/harbor-scanner-aqua/Chart.yaml
- helm/harbor-scanner-aqua/values.yaml
> release: Prepare v0.10.1

- helm/harbor-scanner-aqua/Chart.yaml
- helm/harbor-scanner-aqua/values.yaml
> release: Prepare v0.11.0

- Dockerfile
> chore: Bump up Alpine from v3.9 to v3.13

- helm/harbor-scanner-aqua/Chart.yaml
- helm/harbor-scanner-aqua/values.yaml
> release: Prepare v0.11.1

- Dockerfile
> chore: Bump up Apline base image from 3.13 to 3.14

- helm/harbor-scanner-aqua/Chart.yaml
- helm/harbor-scanner-aqua/values.yaml
> release: Prepare v0.11.2

- .github/workflows/publish-helm-chart.yaml
> chore: Add GitHub workflow to publish Helm charts

- README.md
> docs: Update deployment with Kubernetes

- README.md
- helm/harbor-scanner-aqua/Chart.yaml
- helm/harbor-scanner-aqua/values.yaml
- vagrant/install-aqua.sh
> release: Prepare v0.12.0

- .github/workflows/build.yml
- .github/workflows/publish-helm-chart.yaml
- .github/workflows/release.yml
> chore: Fix path to Helm chart

- .github/workflows/build.yml
- .github/workflows/release.yml
- go.mod
> chore: upgrade Go from 1.16 to 1.17

- CONTRIBUTING.md
- README.md
- Vagrantfile
- vagrant/harbor.yml
> chore: upgrade Aqua to 6.5 and Harbor to 2.4

- README.md
- helm/harbor-scanner-aqua/Chart.yaml
- helm/harbor-scanner-aqua/values.yaml
- vagrant/install-aqua.sh
> release: prepare v0.13.0

- .github/workflows/build.yml
- .github/workflows/release.yml
- README.md
- go.mod
- go.sum
- vagrant/install-go.sh
> chore(deps): bump Go from 1.17 to 1.18

- go.mod
- go.sum
> chore(deps): Pin redigo to v1.8.8

- README.md
- helm/harbor-scanner-aqua/Chart.yaml
- helm/harbor-scanner-aqua/values.yaml
- vagrant/install-aqua.sh
> release: prepare v0.14.0

- .github/workflows/publish-helm-chart.yaml
> chore: release helm chart from git ref

- README.md
> docs: update usage of SCANNER_AQUA_USE_IMAGE_TAG

- helm/harbor-scanner-aqua/templates/secret.yaml
with this commit, corrected secrect.yml for token
> Updated token secret.yml file
